import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import { Toaster } from "@/components/ui/toaster";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full bg-gray-100">
        <div className="min-h-full">
          <main>
            <div className="mx-auto max-w-full">
              <Header />
              <section className="p-8">{children}</section>
              <Footer />
              <Toaster />
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
